### ISSUE TITLE
Errors appear when running Generating_Synthetic_Positive_Samples_FFPred-GAN.py and Classifier_Two_Sample_Tests.py

### ISSUE THREAD

**Issue by KanoHase** [psipred/FFPredGAN#2]
I’m submitting a bug report. 
(This is my first time to send an issue and I'm not a native English speaker, so please let me know if my way of writing was not appropriate)

# Expected Behavior

1. Generating_Synthetic_Positive_Samples_FFPred-GAN.py successfully generates synthetic positive samples.
2. Classifier_Two_Sample_Tests.py successfully selects the optimal synthetic feature samples.

# Current Behavior

1. Generating_Synthetic_Positive_Samples_FFPred-GAN.py stops running, and "SyntaxError: invalid syntax" appears on the screen.
2. Classifier_Two_Sample_Tests.py stops running, and "NameError: name 'iteration' is not defined" appears on the screen.

## Steps to Reproduce

1. Add "+" between "(iteration)" and ""_Synthetic" in line 197.
2. Change the word "iteration" to "epoch", and add "+" between "(epoch)" and ""_Synthetic" in line 31.

## Context

* Operating System : macOS 10.14.6
* Interpreter : Python 3.7.3

**Comment by CenWan** [comment]
Thanks for your report, KanoHase. The bug has been fixed.
